### ISSUE TITLE
title

### ISSUE THREAD

**Issue by Xiufei-x** [Mr-xn/subdomain_shell#1]
大佬你的tmp字典和subnames字典都放在哪个目录底下存放的哪些内容

**Comment by Mr-xn** [comment]
> 大佬你的tmp字典和subnames字典都放在哪个目录底下存放的哪些内容

试试新版的 `run.sh` 脚本 旧版 忘记删除 tmp.txt 『当前运行目录』 那个 `subnames ` 是 ksubdomain 爆破用的 这个脚本用不上 只是用 `ksubdomain` 来验证的
