### ISSUE TITLE
tmp.txt删除的位置可能有问题

### ISSUE THREAD

**Issue by HeyManMan** [Mr-xn/subdomain_shell#3]
<img width="447" alt="image" src="https://user-images.githubusercontent.com/18532708/154420496-9ff14f2a-f416-44c3-bc17-4dd37e612d1c.png">

建议在程序退出前删除即可，在httpx那一行可能删除会存在问题。（我自己改了下，跑起来了）

**Comment by Mr-xn** [comment]
收到 测试后修改,感谢
